name: Create PR for diagram updates

on:
  push:
    branches:
      - diagrams

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract commit message
        id: commitmsg
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: diagrams
          base: main
          title: ${{ steps.commitmsg.outputs.msg }}
          body: |
            updates to diagrams from draw.io. Before merging, please review the changes to ensure they are correct and do not contain any unintended modifications. If you have any questions or concerns about the changes, please feel free to reach out for clarification.
          commit-message: ${{ steps.commitmsg.outputs.msg }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          labels: diagrams
          draft: false
          delete-branch: false
